### ISSUE TITLE
Instantiating with a given graph instance

### ISSUE THREAD

**Issue by jacomyal** [sim51/react-sigma#17]
Currently, as I understand, react-sigma-v2 always initializes itself its own graphology instance.

In some of my applications, I tend to separate my views tree from my data logic, and I like to load my data and to initialize the graphology instance myself. Also, I've had other cases with a graphology instance that always exists (for graph algorithms, for instance), but that is not always displayed using sigma. Finally, as I write right now a classic app rendering GEXF graphs on web pages, it feels really weird to have to instantiate the `SigmaContainer` React component before having an actual graph to give. I always start by managing my data, and **then**, I deal with rendering.

For those cases, it would really help to allow giving react-sigma-v2 a graphology instance.

**Comment by sim51** [comment]
With v2, it's possible, you can take a look at the live example : https://sim51.github.io/react-sigma/docs/example
