### ISSUE TITLE
Adding cluster layer

### ISSUE THREAD

**Issue by from81** [sim51/react-sigma#19]
Hi... Sorry this might be a noob question..
Is it possible to insert a div layer between canvas layers that are inside of the SigmaContainer? 
I'm trying to add cluster layer like shown in this example, which I found from sigma.js github repo: https://codesandbox.io/s/github/jacomyal/sigma.js/tree/main/examples/clusters-labels?file=/index.ts:379-455

I have `const container = document.getElementById('sigma-container')` inside of <SigmaContainer> and it's always null, presumably because it's located inside of the said element. I know this might now even be related to react-sigma-v2 specifically, but I'd really appreciate it if someone can point me in a direction!

**Comment by sim51** [comment]
In the context you will have access to thte sigma container : https://github.com/sim51/react-sigma-v2/blob/1.3.0/src/context.ts#L6

So something like that should do the trick : 

```
import { useSigmaContext } from "react-sigma-v2/lib/esm/context";

export const MyCustomGraph: FC = () => {
  const sigmaContext = useSigmaContext();
  
  useEffect(() => {
      const clustersLayer = ...
      
      sigmaContext.container.insertBefore(clustersLayer, document.getElementsByClassName("sigma-hovers")[0]);
  }, [sigmaContect.container])

  ...
}
```

The context is not exposed in the lib per default, that's why I import it with the path lib/esm ...
I will change that in the futur.

FYI, I'm preparing a v2 of this lib that should be released at the end of this month. 
I will include this issue that is totally legit.

Thanks !

**Comment by sim51** [comment]
See #20

**Comment by sim51** [comment]
FYI, the sigma container in this lib has no HTML ID (an app can have many sigma instance in the same page), so there is just a class.
You can also try : `const container = document.getElementsByClassName('sigma-container')[0]`

**Comment by from81** [comment]
Thanks! I'llve give it a try.
I've been using react-sigma-v2 and it's great! https://anu-graph-vis.vercel.app/courses

**Comment by from81** [comment]
@sim51 
Is there a list of available parameters for the <SigmaContainer> props? Specifically, I'm looking for a way to change the threshold at which node labels are shown/hidden.

As shown in the image below, I need to lower the threshold at which node labels are shown, so that at the initial load only the cluster labels are visible.

![image](https://user-images.githubusercontent.com/34954529/148644005-4738d5a6-8b39-4e2a-916c-093c008d5af2.png)

**Comment by from81** [comment]
Realized I was thinking about it the wrong way. Adjusted the `labelRenderedSizeThreshold` property of `SigmaContainer` and achieved desired outcome:
![Screen Shot 2022-01-10 at 02 33 29](https://user-images.githubusercontent.com/34954529/148689160-25b1b8d5-e8bf-4712-a8d5-4556538088d4.jpg)

**Comment by sim51** [comment]
It seems you found the solution, so I'm closing this ticket
