### ISSUE TITLE
Sigma instances are not killed when component is unmounted

### ISSUE THREAD

**Issue by jacomyal** [sim51/react-sigma#21]
I have an application where I mount and unmount often my sigma component, while I have another instance behind that is always there.
At some point, since the sigma instances are not killed which makes the WebGL contexts leak, the main instance (the one behind) stopped working.

**Comment by sim51** [comment]
But normally it should be killed : https://github.com/sim51/react-sigma/blob/1.3.0/src/SigmaContainer.tsx#L83-L91

**Comment by sim51** [comment]
Closing it due to inactivity and not reproducibility.
