### ISSUE TITLE
Replace the example with story book 

### ISSUE THREAD

**Issue by sim51** [sim51/react-sigma#26]
Can be very cool, especially if I publish it with the website

**Comment by boris-lapouga** [comment]
Just a couple of examples with hooks, events and more interactivity should cover the need. Right now it's pretty in-the-context and hard to understand from the provided documentation

**Comment by sim51** [comment]
The example project is kept, it is used for developer to test their features and also E2E test.

I found a way on docusaurus to add code/preview block code., and I started to write examples.
Exemple :  https://sim51.github.io/react-sigma/docs/example/load-graph

So what I need now, is a list of examples that should be created.
