### ISSUE TITLE
Edge labels do not appear in the example

### ISSUE THREAD

**Issue by brianjychan** [sim51/react-sigma#29]
**Summary**: 
edge names dont display properly on the example at https://sim51.github.io/react-sigma/docs/example. I'm trying to follow the example to implement react-sigma myself, but am also facing the problem of edges not showing. it would be great if the example showed the full code as well.

<img width="1323" alt="Screen Shot 2022-06-27 at 10 00 30 PM" src="https://user-images.githubusercontent.com/34144740/176096602-6023d727-4f23-4733-81da-c624e6d6ed47.png">

**To help us understand your issue, please specify important details, primarily**:
- React-sigma-v2 version: 1.3.0
- Sigma.js version : X.Y.Z
- Graphology version : X.Y.Z
- Operating system: Mac OS
- Web browser: Chrome, Safari, Brave are tested to have this error
- **Steps to reproduce**: see https://sim51.github.io/react-sigma/docs/example, edge names dont display
- Expected: edge names show
- Actual behavior: no edge names

**Comment by sim51** [comment]
By default sigma.js disable the render of edge label.
You have to enable it : ` <SigmaContainer graph={graph} style={{ height: "500px" }} initialSettings={{renderEdgeLabels:true}}>`
