### ISSUE TITLE
labelColor and edgeLabelColor not behaving as expected

### ISSUE THREAD

**Issue by suryarastogi** [sim51/react-sigma#34]
## `labelColor` and `edgeLabelColor` not behaving as expected

- React-sigma-v2 version: 3.0.3
- Sigma.js version : 2.3.1
- Graphology version : 0.25.0
- Operating system: Mac and CodeSandbox
- Web browser: (for example Firefox 82.0.2)

### Steps to reproduce 
Use either of the following settings in a graph
```
settings={{
    edgeLabelColor: "#0f0",
    labelColor: "#f00"
  }}
```
Reproducible [CodeSandbox link](https://codesandbox.io/s/epic-joana-zhrvwf?file=/src/App.js:901-1046)

### Expected behaviour
Edge labels are coloured green and node labels are coloured red

### Actual behaviour
Edge labels are coloured black and node labels are not legible

### Note
I've used Sigma.js in the past but I'm somewhat new to React so there is a chance I may be using the library incorrectly

**Comment by sim51** [comment]
Settings are wrong, try this instead :

```
settings={{
   labelColor: { color: "#f00" },
   edgeLabelColor: { color: "#f00" }
  }}
```

**Comment by suryarastogi** [comment]
Thank you! That works!
