### ISSUE TITLE
[website] Example on controls and how to use them

### ISSUE THREAD

**Issue by sim51** [sim51/react-sigma#35]
Zoom, fullscreen and control container with the position, ...
how to customize the icons

**Comment by therhappy** [comment]
Hello!
This example would come really handy to me. I am upgrading a project from the "react-sigma-v2" era, so the previous paradigm was to import the controls from the lib:
`
import { SigmaContainer, ZoomControl, FullScreenControl } from "react-sigma-v2";
(...)
// provide controls in component return
<ZoomControl
      className="ico"
      customZoomIn={<BsZoomIn />}
      customZoomOut={<BsZoomOut />}
      customZoomCenter={<BiRadioCircleMarked />}
    />
`

While the components such as ZoomControl can be imported from "@react-sigma/core", these can't be used in the exact same way. For instance, the above implementation with a new import would yield:

`
ERROR in src/views/Root.tsx:113:17
TS2322: Type '{ className: string; customZoomIn: Element; customZoomOut: Element; customZoomCenter: Element; }' is not assignable to type 'IntrinsicAttributes & ZoomControlProps & { children?: ReactNode; }'.
  Property 'customZoomIn' does not exist on type 'IntrinsicAttributes & ZoomControlProps & { children?: ReactNode; }'.
    111 |               <ZoomControl
    112 |                 className="ico"
  > 113 |                 customZoomIn={<BsZoomIn />}
        |                 ^^^^^^^^^^^^
    114 |                 customZoomOut={<BsZoomOut />}
    115 |                 customZoomCenter={<BiRadioCircleMarked />}
    116 |               />
`

From the current documentation stub (https://sim51.github.io/react-sigma/docs/example/controls) it seems the individual controls must not be supplied separately but instead must be part of a single ControlContainer. So my attempt was to replace the previous separate controls from the existing version to : 
`
import { SigmaContainer, ControlsContainer } from "@react-sigma/core";
// ...
<ControlsContainer position="bottom-left" />
`

Which does not cause any error but does not render controls either! I'll try to read through the code but just a basic example to replicate what exists in the sigma-react demo (on sigma.js website, still based on react-sigma-v2) would be great 😃

**Comment by sim51** [comment]
You can take a look here https://github.com/sim51/react-sigma/blob/main/project/packages/examples/src/views/custom-buttons.tsx

**Comment by sim51** [comment]
https://sim51.github.io/react-sigma/docs/example/controls/
