### ISSUE TITLE
Dynamically changing/setting arrow size of an edge

### ISSUE THREAD

**Issue by BaherZ** [sim51/react-sigma#40]
**Is your feature request related to a problem? Please describe.**
Being able to dynamically set arrow size without affecting the edge size (by dynamically I mean allow the user to do via input)

**Describe the solution you'd like**
Something close to the canvas solution we previously had in v1 (canvas version) maybe?
```
<SigmaContainer
                        settings={{
                            nodeProgramClasses: {image: getNodeProgramImage(), circle: CircleNodeProgram},
                            edgeProgramClasses: {
                                arrow: ArrowEdgeProgram,
                            },
                            minArrowSize: 100, //here the minArrowSize can be dynamically set
                            ...graphSettings,
                        }}
                        style={{height: '100%', background: props.noBackground ? 'white' : mainBackgroundColor}}
                    >
```

**Comment by sim51** [comment]
This is not related to `react-sigma` but to `sigma`.
Please open a request feature ticket on the Sigma repo directly.

**Comment by BaherZ** [comment]
For anyone wondering in the future, I posted this answer here:

https://stackoverflow.com/questions/74287062/how-to-dynamically-change-set-arrow-size-of-an-edge-in-sigma-v2/74287630#74287630
