### ISSUE TITLE
Invalid graph instance - when trying to add nodes then using the input bar

### ISSUE THREAD

**Issue by iliaspdx** [sim51/react-sigma#41]
## Problem
Hello everyone, I'm trying to dynamically add nodes with some sort of click or modal, or anything. But the moment I start to use the search bar from <SearchControl /> or the modal or anything that contains an input box, I get this 

- `[error](react-dom.development.js:22839 Uncaught Error: Sigma: invalid graph instance.)` 
- and `The above error occurred in the <ForwardRef> component:`

I haven't seen any examples where you can dynamically add individual nodes one by one with some sort of input box, which is why I'm posting here

## Code
Here is the code. I simplified it to just have the `<SearchControl />` and still get the same error

``` 
import { useEffect, useState } from "react";
import MultiUndirectedGraph from "graphology";
import { SigmaContainer, useLoadGraph, useRegisterEvents, ControlsContainer, SearchControl } from "@react-sigma/core";
import "@react-sigma/core/lib/react-sigma.min.css";
import { v4 as uuidv4 } from 'uuid'; 

const TestPage = () => {
  const [graph, setGraph] = useState(new MultiUndirectedGraph());

  const GraphEvents = () => {
    const registerEvents = useRegisterEvents();

    useEffect(() => {
      // Register the events
      registerEvents({
        click: (event) => {
          // graph = new MultiUndirectedGraph();
          setGraph(
            graph.addNode(uuidv4(), { x: event.x, y: event.y, label: "A", size: 10, color: "#FA4F40" })
          );
          console.log("click", event.x, event.y)
        },
      });
    }, [registerEvents]);

    return null;
  };
  return (
    <div className="static w-screen h-screen">
      <SigmaContainer 
        id="container"
        graph={graph}
        settings={{ renderEdgeLabels: true}}
      >
        <ControlsContainer>
          <SearchControl />
        </ControlsContainer>
        <GraphEvents />
      </SigmaContainer>
    </div>
  );
};

export default TestPage
```

## More info

- Sigma.js version : 2.4.0
- Graphology version : 0.25.1
- Operating system: Windows 10
- Web browser: Chrome
- **Steps to reproduce**
- Expected behavior: Click the graph to create a new node, then use the search bar to type whatever I want (eventually would like to create a new node, etc)
- Actual behavior: error after creating a new node and then typing into the search bar

**Comment by sim51** [comment]
This part of the code is wrong : 

```
setGraph(
  graph.addNode(uuidv4(), { x: event.x, y: event.y, label: "A", size: 10, color: "#FA4F40" })
);
```

`graph.addNode` doesn't returned a `graph` instance, so when you set it, yes the graph is invalid.
You should remove the `setGraph` and just mutate the `graph` object.
Take a look here : https://codesandbox.io/s/react-sigma-example-forked-n1p4em?file=/src/App.tsx

**Comment by iliaspdx** [comment]
Wow can't believe I miss that. Thank you so much, it makes a lot of sense now!
