### ISSUE TITLE
Tooltip support when a node event happens (dbl click, hover, etc)

### ISSUE THREAD

**Issue by BaherZ** [sim51/react-sigma#52]
## Feature request template

I do not think there is a current way where we can have a tooltip when we for example double-click on a node, something like this existed in the form of a plug-in Sigma 1.0, I wonder if we have this in react sigma.

**Comment by sim51** [comment]
Such a feature doesn't exist on react-sigma, you have to write the component.

You have to register an event on the double click node, and then do what you want.
In the event you have the mouse position, and also the node that has been clicked, so you have everything you need to do it.
