### ISSUE TITLE
Error after deleting a node

### ISSUE THREAD

**Issue by jMoulis** [sim51/react-sigma#53]
Hello,
I'm brand new using the lib.
I'm trying to add, for testing purpose, a doubleclick on a node to drop it. But I catch th following error:
`Uncaught NotFoundGraphError: Graph.neighbors: could not find the "48309" node in the graph.`, which seems pretty normal, because I just deleted.
I tried to use a cleaning function in the `graph.on('nodeDropped')`, but I can't get it working.
Can you help me?
Best regards

react-18
react-sigma 3.0.0

**Comment by sim51** [comment]
Hi,
Can you provide your code or make and example on codesandbox ?
