### ISSUE TITLE
`ref` is not generic

### ISSUE THREAD

**Issue by kristof-mattei** [sim51/react-sigma#58]
## `ref` is not generic

`ref` is not generic. This causes a mismatch between `ref={setSigma}` and the actual type of `setSigma`.

We give it `setSigma`: `React.Dispatch<React.SetStateAction<Sigma<MyGraph> | null>>` 

but the `ref` enforces `setSigma`: `React.Dispatch<React.SetStateAction<Sigma<AbstractGraph<Attributes, Attributes, Attributes>> | null>>` 

**React-sigma-v2:**  3.4.2
**Sigma.js version:** 2.4.0
**Graphology version:** 0.25.4
**Operating System:** LG Laundry machine OS
**Web browser:** Edge 120.0.0

### Steps to reproduce

Check the live example https://codesandbox.io/p/sandbox/react-sigma-example-forked-9mks58?file=%2Fsrc/App.tsx

### Expected behavior

I can use `setSigma` with custom graph type so I can get better intellisense

### Actual behavior

Computer says no:

![image](https://github.com/sim51/react-sigma/assets/864376/1421b3d1-89ea-4b5b-80a4-14d45133d914)

## Note

If the issue has an inactivity of **30 days**, it becomes stale.
With an additional inactivity of **14 days**, the issue is closed

**Comment by sim51** [comment]
Done with the latest version of sigma (ie. the v3).
Take a look here : https://github.com/sim51/react-sigma/blob/main/packages/storybook/stories/External.tsx#L13
