### ISSUE TITLE
fail to import in vite project because of lodash

### ISSUE THREAD

**Issue by HananoshikaYomaru** [sim51/react-sigma#64]
![CleanShot 2024-04-04 at 13 23 12@2x](https://github.com/sim51/react-sigma/assets/43137033/9462d3b0-3223-42b8-9f08-78a7b949c269)

there is only two uses of lodash in the project. is it possible to replace it with a different package? Or otherwise change it to use default export but that might affect the tree shaking.

**Comment by sim51** [comment]
Thanks ! 
Will do a new release today.

**Comment by sim51** [comment]
Should be fixed in v4.0.1
