### ISSUE TITLE
sigma.getGraph().setNodeAttribute(event.node, "highlighted", true) problem

### ISSUE THREAD

**Issue by pann-q** [sim51/react-sigma#68]
Good day. We are trying to get an existing graph in a clickNode action 
 in registerEvents. We need to change the "highlighted" property, but an error appears: "Graph.setNodeAttribute: could not find the "test00001" node in the graph"

```
const Events: FC = () => {
  const registerEvents = useRegisterEvents();
  const dispatch = useAppDispatch();
  const sigma = useSigma();

  useEffect(() => {
    registerEvents({
      clickNode: (event) => {
        sigma.getGraph().setNodeAttribute(event.node, "highlighted", true);
```

Version 
    "@react-sigma/core": "^3.4.2",
    "sigma": "^2.4.0",
    "graphology": "^0.25.1",
    "graphology-types": "^0.24.7"

we tried to update packages to "@react-sigma/core": "^4.0.2", 
    "sigma": "^3.0.0-beta.16",
but an error appeared for import getNodeProgramImage from "sigma/rendering/webgl/programs/node.image" - path does not exist

- Operating system: Windows 10
- Web browser: Google Chrome 125.0.6422.78 
- Expected behavior
Node highlighted
- Actual behavior
Error: Graph.setNodeAttribute: could not find the "test00001" node in the graph.

**Comment by sim51** [comment]
I tried to reproduce your issue here : https://codesandbox.io/p/sandbox/react-sigma-issues-68-543ydn
But it works... can give me the full version of your code, specially the deps of your `useEffect` ?

**Comment by pann-q** [comment]
> I tried to reproduce your issue here : https://codesandbox.io/p/sandbox/react-sigma-issues-68-543ydn But it works... can give me the full version of your code, specially the deps of your `useEffect` ?

Good day, i used your example and it works, thank you very much!

**Comment by sim51** [comment]
Good news !
So i close the ticket
